#!/usr/bin/python
# Mound Data Manager <https://launchpad.net/mound>
# Copyright (C) 2009-2010 Jacob Peddicord <jpeddicord@ubuntu.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import sys

# i18n
import locale
import gettext
locale.setlocale(locale.LC_ALL, '')
gettext.install('mound', '/usr/share/locale', unicode=True)

# we have a gui
if len(sys.argv) == 1:
    import gtk
    from Mound.ui import MainUI
    from Mound.userdata import UserData
    
    ud = UserData()
    ud.load_defaults()
    ud.load_applications()
    ui = MainUI(ud)
    ui.load_applications()
    gtk.main()
# console mode
else:
    from Mound import run_cli
    sys.exit(run_cli())

